### PR TITLE
Freebsd fixes

### PR DESCRIPTION
**Pull request by mgamsjager**
Add additional fixes for FreeBSD

### CODE REVIEW

**Comment by mgamsjager** [comment]
image

**Comment by cjbassi** [comment]
Copying your comment to clarify what this fixes:
> fixes the temperature, small fix for the process list and adds basic swap info

I also added a couple commits and changed the merge from master to a rebase onto master to cleanup git history.

Fixes #134 

So there's a couple issues left to fix here:
1. we should try to minimize the overlapping code between `mem_freebsd.go` and `mem_other.go`
2. in `mem_freebsd.go`, `self.Data["Swap"]` is appended 0 instead of the used percentage
3. in `mem_freebsd.go`, `self.Labels["Swap"]` has a different formatting than in `mem_other.go`
4. we can probably remove the `temperature` suffix in the temperatures in the temperature widget

Otherwise it looks good.

**Comment by mgamsjager** [comment]
Changed couple of things you mentioned. Let me know if you agree on the abstraction of the memory render function `renderMemInfo`

**Comment by cjbassi** [comment]
Awesome, this looks good now. Thanks for the work on this! I think we can merge it now.

**Pull request merged**
