### PR TITLE
remove vendor

### PR DESCRIPTION
**Pull request by h8liu**

### CODE REVIEW

**Comment by h8liu** [comment]
otherwise `github.com/cjbassi/gotop/src/widgets` won't build without go modules.

**Comment by h8liu** [comment]
example build failure: https://gopkgs.io/builds/20181130-022153-94e30741

**Comment by cjbassi** [comment]
Thanks, I forgot I was vendoring but I would actually like to delete the vendoring if I can. Would/does gotop run correctly without a vendor directory?

**Comment by cjbassi** [comment]
For someone without Go modules I mean?

**Comment by cjbassi** [comment]
Thanks, that makes sense. I'll merge this and add a notice to the README about `go get`ing requiring Go 1.11+.

**Pull request merged**
