### PR TITLE
Implement snap packaging, snaps are universal linux packages (#119)

### PR DESCRIPTION
**Pull request by Lin-Buo-Ren**
This patch implements the necessary details to package gotop as a snap that can be run on a broad range of supporting GNU/Linux distributions[1].

[1] https://snapcraft.io/

Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>

### CODE REVIEW

**Comment by cjbassi** [comment]
Thanks a lot for the work you've put into this! And I'm glad you were able to get all the widgets to work by using the various snap plugins. I saw from the video you linked previously that not all the widgets work out of the box.

I'm not too familiar with snap, so a couple questions: Should I create a snap account and publish the snap under my own gotop-foo package name? And do I need to publish a new snap on each release?

And I'm planning on contacting @dawndiy at some point, but I'd like to get this figured out first.

**Comment by Lin-Buo-Ren** [comment]
> Should I create a snap account and publish the snap under my own gotop-foo package name?

A snap developer(or to be specific, an [Ubuntu One](https://login.ubuntu.com)) account is required to publish the snap in the Snap Store.  Whether using which package name is another issue.

> do I need to publish a new snap on each release?

If you set-up the [snapcraft build service](https://snapcraft.io/build) it will build and publish a snap on every code push to the repository, you can promote the snap of the stable release to the stable risk channel via [the releases page](https://snapcraft.io/gotop-brlin/releases):

demo snap promote opt

**Comment by Lin-Buo-Ren** [comment]
I just added your e-mail address to the snap's collaborator list, you can now access [the snapcraft build service page](https://build.snapcraft.io/user/Lin-Buo-Ren/gotop), and the [new](https://snapcraft.io/gotop-brlin/listing) and [legacy](https://dashboard.snapcraft.io/snaps/gotop-brlin) snap administration page after login with the [Ubuntu One](https://login.ubuntu.com) account associate to it.

**Comment by Lin-Buo-Ren** [comment]
I changed the snap name to `gotop-cjbassi` for now.

**Comment by Lin-Buo-Ren** [comment]
I somehow got the pull request messed up so I recreated it again, please review.

**Comment by cjbassi** [comment]
Cherry picked the commit onto master in 0817bea2bb18880bea0710aa0214eff7088fa04b, so this is effectively merged. Thanks!

**Pull request closed without merging**
